#214 refactor : 동시성 제어 비관적 락 설정
Floney-2023/Floney-Server pull request #216
Opened 2023-10-17 13:02 UTC by sienna011022

## 📚 이슈 번호
#214

## 📝 데이터베이스 변경 사항

## 💬 기타 사항
다음과 같은 쿼리에 락을 걸어 놓았습니다

참여 희망 가계부의 인원 체크 쿼리 (동시에 가계부 참여 가능성)
유효 가계부 확인 (동시에 가계부 삭제 가능성)
참여 중인 모든 가계부원 조회 (동시에 가계부원 참여 가능성)
가계부 조회(여러 쿼리에서 충돌 발생 가능성)
현재 내가 참여중인 가계부 조회(동시에 가계부 삭제 가능성)

2023-10-18 11:10 UTC, dahyen0o requested changes
비관적 락을 건 쿼리 메서드 이름에는 `~Exclusively` 처럼 락을 걸었다는 것을 알 수 있게 추가해서 표시하는 게 좋을것 같습니다! 같은 쿼리인데 락을 걸지 않고 가져오는 경우도 생길 수 있어서요

2023-10-25 13:57 UTC, dahyen0o approved these changes
최종적으로 리뷰 끝나면 제가 컨플릭트 수정후 머지하겠습니다... 허허

2023-10-25 13:57 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/repository/BookRepository.java
>      Optional<Book> findBookByBookKeyAndStatus(String bookKey, Status status);
JPARepository 사용하면 메서드 이름에 exclusively 덧붙이는게 안되나요?

2023-10-25 13:57 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/service/BookServiceImpl.java
>      }
이 메서드에서도 비관적 락을 걸어야 하나요?

2023-10-25 14:12 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/repository/BookRepository.java
>      Optional<Book> findBookByBookKeyAndStatus(String bookKey, Status status);
넵 마자여 named 쿼리는 정해진 규칙대로 써야해욤

2023-10-25 14:13 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/service/BookServiceImpl.java
>      }
아아 비관적 락 쓰면서 다같이 고쳐져서..요기는
락 안걸린 countInBook만 따로 필요하겠네요..

2023-10-25 17:05 UTC, dahyen0o commented
@sienna011022 성윤님 컨플릭트 해결 전 JPA 쿼리 메서드에 비관적 락 걸린 경우 다시 살펴보고 질문 드립니다..!

-  `BookService.findUsersByBook()` 내 `bookUserRepository.findAllByBookAndStatus()`
	이 때의 비관적 락이 의미가 있을까요? 중간에 비활성화 된 유저가 응답에 포함되거나, 활성화 된 유저가 포함되지 않는 경우 둘 다 상관이 없을 것 같아서요! 특히 현재는 정산 추가를 위해 쓰이는데, 이 API로 가계부원을 조회해도 이후에 탈퇴 또는 참여가 일어날 수 있어서 의미가 없어 보입니다. 여기서 락을 걸지 않고, 정산 추가 API에서 유저에 대해 유효성을 검증하는 로직이 추가되어야 할 것 같아요

- `BookService.getBookInfoByCode()` 내 `bookRepository.findBookByCodeAndStatus()`
	이 API의 요청과 응답 사이에 해당 가계부가 비활성화되어도 (또는 가계부의 아무 데이터가 변경되어도) 상관없지 않을까요?

- `AnalyzeService.analyzeByBudget()` 내 `bookRepository.findBookByBookKeyAndStatus()`

등등.. 요청을 처리하는 중간에 해당 데이터가 변경되어도 상관없어 보이는 (정합성이 중요하지 않은) 곳들이 많아 보여서 다시 확인 부탁드립니다 ㅠㅠ! 비관적 락을 거는 순간 해당 데이터를 동시적으로 사용하는 모든 요청에 대기가 걸려 최대한 필요없는 부분은 덜어내는 게 좋을 것 같아요

추가로 JPA로 생성한 쿼리 메서드에서 이름 중간에 문자열을 추가하는 건 가능해서 이건 수정했습니다!

2023-10-26 10:42 UTC, sienna011022 commented
1. 아하 넵 ! 알겠습니다.
2.  음..근데 밑에 코드는 가계부에 참여하는 로직인데 만약 조회하는 순간에 가계부가 삭제된다면, 이후 코드들이 딱히 book이 active인지 잡는 코드가 없어서 유저는 결국 없는 가계부에 참여하게 되지 않나요?
<pre>
@Override
    @Transactional
    public CreateBookResponse joinWithCode(CustomUserDetails userDetails, CodeJoinRequest request) {
        String code = request.getCode();
        String userEmail = userDetails.getUsername();
        User user = userDetails.getUser();

        Book book = bookRepository.findBookByCodeAndStatus(code, ACTIVE) //여기서 안잡으면 
            .orElseThrow(() -> new NotFoundBookException(code));

        // 현 유저의 가계부 참여 개수 체크 //book체크 X
        checkCreateBookMaximum(user);

        // 참여 희망 가계부 정원 체크 //book체크는 안함
        isMaxBookCapacity(book);

        // 이미 존재하는 가계부 유저인지 체크
        if (bookUserRepository.findBookUserByCode(userEmail, request.getCode()).isPresent()) {
            throw new AlreadyJoinException(userEmail);
        }

        saveDefaultBookKey(userDetails.getUser(), book);
        bookUserRepository.save(BookUser.of(userDetails.getUser(), book));

        return CreateBookResponse.of(book);
    }

</pre>

3. 이것도 countInBook과 마찬가지로 한번에 수정하면서 다같이 수정되었네요. 락 필요 없는 애들이랑 분리해놓겠습니다

2023-10-26 11:03 UTC, sienna011022 commented
일단 제 판단하에 다시 분리했습니다.
세은님이 다시 보시고 의견 주시고 수정하셔도 될 것 같아요

----

다만 의문인건 BookService.makeInitBook() 메서드는 [가계부 초기화]하기 메서드인데...락이 필요할까요?(지금은 안걸었어요)
초기화를 하는 순간, 누군가 내역을 추가해도 어쩔 수 없다고 생각하는데.. 음 어떻게 생각하시는지 궁금합니다

2023-10-28 07:35 UTC, dahyen0o commented
@sienna011022 
> 다만 의문인건 BookService.makeInitBook() 메서드는 [가계부 초기화]하기 메서드인데...락이 필요할까요?(지금은 안걸었어요)
> 초기화를 하는 순간, 누군가 내역을 추가해도 어쩔 수 없다고 생각하는데.. 음 어떻게 생각하시는지 궁금합니다

말씀하신 상황에서 락을 걸지 않는다면 가계부를 초기화하는 도중에 해당 가계부에 관련 데이터(내역 등등)이 추가 될 수 있는데, 저는 막아야 한다고 생각합니다. 현재 currency를 바꾸는 경우에도 해당 메서드로 가계부 초기화를 하고 있기 때문에 이전 currency를 사용한 내역이 추가되면 안될 것 같아서요! 그러면 아예 두 상황(가계부 초기화 요청, currency 변경 요청)을 분리해서 전자는 락을 걸지 않고 후자는 락을 걸게 리팩토링 하는 게 나을 것 같습니다...

2023-10-28 10:59 UTC, sienna011022 commented
> 황(가계부 초기화 요청, currency 변경 요청)을 분리해서 전자는 락을 걸지 않고 후자는 락을 걸게 리팩토링 하는 게 나을 것 같습니다...

흠 근데 이게 [단위]만 변경되는거지, 그 가계부 내용에 작성 되는건 금액 그대로이기 때문에 문제 없지 않을까요?
현재 프로세스는 다음과 같아요 가계부 내역 금액 1000 작성 + $화폐 단위 조회 => 사용자 눈에 1000$가 보임

즉 금액과 단위를 따로  조회하기에 말씀하신 사항은 문제가 없을것 같은데..어떻게 생각하시나요

2023-10-30 07:18 UTC, dahyen0o commented
> 즉, 금액과 단위를 따로 조회하기에 말씀하신 사항은 문제가 없을것 같은데..어떻게 생각하시나요

@sienna011022 사용자가 1000원을 의도하고 추가했을 때 1000엔으로 다르게 추가되어도 상관없다는 말씀이시죠?
큰 문제는 아니라 성윤님 말대로 딱히 필요없어도 될 것 같긴 합니다

2023-10-30 07:29 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/repository/BookRepository.java
> -    Optional<Book> findBookExclusivelyByBookKeyAndStatus(String bookKey, Status status);
@sienna011022 엇 메서드 이름이랑 내용 보고 그냥 마지막으로 봤던 가계부 정보 돌려주는 줄 알았네요 수정하겠습니다~!

2023-10-30 08:21 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
> +    public boolean existsByBookKeyAndUserEmail(final String bookKey, final String userEmail) {
아뇨 정산 쪽 코드 리팩토링했습니다!

2023-10-30 08:45 UTC, merged

2024-01-18 10:41 UTC, sienna011022 commented
```
1. PR 본문 - 참여 희망 가계부의 인원 체크 쿼리 (동시에 가계부 참여 가능성)

2. 세은님 댓글 - 말씀하신 상황에서 락을 걸지 않는다면 가계부를 초기화하는 도중에 해당 가계부에 관련 데이터(내역 등등)이 추가 될 수 있는데, 저는 막아야 한다고 생각합니다.
```
두건에 대해서 이번에 동시성 쪽 다시 공부하다가, 생각해봤는데  for update로는 insert는 못 막기 때문에  `가계부를 초기화하는 도중에 가계부 내역이 추가될수 있는데` 와 동시에 가계부 참여 가능성이라는 문장에 오류가 있다고 생각하는데 맞나요?

+ 덧붙이자면 1번에 대한 락 필요 이유는 가계부 참여 가능성이라기 보다는 기존 회원이 가계부를 나가서 ACTIVE를 INACTIVE로 바꾸는 경우가 이유가 될것 같고요

2024-01-24 04:11 UTC, dahyen0o commented
@sienna011022 
아마 저 때 fk가 걸려있던 상태라 fk check 때문에 얘기한 거 같은데 오래되어서 기억이 잘 안나네요
우선 부모 데이터에 쓰기 락이 걸려있는 경우 자식 데이터를 추가할 때 대기가 생기는 건 맞습니다. ([참고](https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html#foreign-key-locking))
지금은 인덱스만 걸려있어 말씀대로 insert를 못막고요