231 feature 구독 시작 시 가계부 정원 증원
Floney-2023/Floney-Server pull request #232
Opened 2023-11-01 12:57 UTC by sienna011022

## 📚 이슈 번호
#231

## 📝 데이터베이스 변경 사항

## 💬 기타 사항

2023-11-01 16:20 UTC, dahyen0o requested changes
슬랙에 남긴 댓글도 (패키지 관련) 확인 부탁드립니다 🙇‍♀️

2023-11-01 16:20 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/entity/Book.java
> +    }
update보다 구체적으로 '구독' 상태가 되었다는 의미가 담긴 네이밍이 좋을것 같습니다!
구독 해제되었을 때도 capacity가 업데이트 되니까요

2023-11-01 16:20 UTC, dahyen0o commented on src/main/java/com/floney/floney/user/service/SubscribeService.java
> +            .collect(Collectors.toList());
`toList()` 와 `collect(Collectiors.toList())`의 차이가 뭔가요?

2023-11-01 16:20 UTC, dahyen0o commented on src/main/java/com/floney/floney/user/service/SubscribeService.java
> +        return delegateResult;
1. 랜덤으로 비활성화하기로 한 건 기획쪽과 얘기된 사항인가요?
2. 위임 로직이 구독자가 있으면 위임, 없으면 비활성화여서 어떻게 `위임되지 않은 활성 가계부` 가 남아있을 수 있지 했는데 `bookUserRepository.findRandomBookUserWhoSubscribeExclusively()` 쿼리에서 현재 방장을 포함시켜서 랜덤 유저를 조회하고 있네요..? 이러면 여러 명 있는 가계부에서도 위임이 제대로 일어나지 않을 수 있어서
현재 방장을 제외한 구독자 랜덤 조회 후 있으면 위임, 없으면 비활성화 → 비활성화 and 인원 한 명인 가계부 중 정책대로 하나 활성화 => 이런 식으로 수정해야 할 것 같습니다

2023-11-01 16:20 UTC, dahyen0o commented on src/main/java/com/floney/floney/user/service/SubscribeService.java
> +        return delegateResult;
그리고 똑같은 메서드가 bookService에도 있어서(위임) 이것도 같이 수정해야 할듯요...!

2023-11-03 12:21 UTC, sienna011022 commented on src/main/java/com/floney/floney/user/service/SubscribeService.java
> +            .collect(Collectors.toList());
똑같은데, java 16부터 toList()가 나왔고 그 전까진 collect(Collectors.toList())를 썻다고 하네여.toList()로 변경해놓을게요

2023-11-03 12:31 UTC, sienna011022 commented on src/main/java/com/floney/floney/user/service/SubscribeService.java
> +        return delegateResult;
1 . 음 뭔가 옛날에 그렇게 결정된 것 같은데 다시 증적 남길게요

2 - (1). 말씀하신 `findRandomBookUserWhoSubscribeExclusively()`는 현재 방장을 포함해도 상관이 없을 것 같은데요.
방장이 구독을 해지했으니 항상 포함되지 않은 상태로 조회 될 것이라고 생각됩니다

2 - (2). 현재 위임 처리는 가계부가 `isOverSubscribeLimit()`에 걸릴 때(가계부 원이 2명 초과인 경우)만 위임 처리 됩니다. 즉, 구독 중인 가계부여도 2명이하의 정원을 지닌다면 `isOverSubscribeLimit()`에 걸리지 않아서 위임 로직에서 처리되지 않죠. 

예시로 만약 사용자의 가계부가 다음과 같은데 구독을 해지한다면..
가계부 A : 내가 방장 사용자 나 포함 2명
가계부 B : 내가 방장 사용자 나 포함 2명

위임처리가 될 필요도 없음 && but 가계부 1개는 비활성화를 해야 해서 이번에 remainBooks를 도입하게 된 것 입니다.

-----
뭔가 비슷한 내용을 얘기하는 것 같은데, 애매해서 다시 정리해서 말씀 드려요

2023-11-03 15:34 UTC, dahyen0o reviewed
엇 제가 얘기한 것은 아래였는데 바꾸셔서 하셨네요..!
- 구글 토큰 코드: infra 패키지
- 가계부 알람 코드: alarm 패키지

저는 구글 토큰이 사용자 요청이 아니라 클라이언트 서버에서의 요청이라 이게 infra에 들어가고, 가계부 알람은 다른 도메인과 성격이 비슷하기 때문에 alarm 패키지에 두는 게 적절하다 생각했거든요. 성윤님은 어떠세요?

2023-11-04 12:24 UTC, sienna011022 commented
> 엇 제가 얘기한 것은 아래였는데 바꾸셔서 하셨네요..!
> 
> * 구글 토큰 코드: infra 패키지
> * 가계부 알람 코드: alarm 패키지
> 
> 저는 구글 토큰이 사용자 요청이 아니라 클라이언트 서버에서의 요청이라 이게 infra에 들어가고, 가계부 알람은 다른 도메인과 성격이 비슷하기 때문에 alarm 패키지에 두는 게 적절하다 생각했거든요. 성윤님은 어떠세요?

앗 넵넵 동의합니댜

2023-11-04 12:54 UTC, dahyen0o approved these changes
👍

2023-11-04 13:03 UTC, merged