#325 fix : 분석 카테고리 조회 시, 이름이 아닌 객체 자체를 쿼리문에 조건으로 지정
Floney-2023/Floney-Server pull request #326
Opened 2023-12-10 12:54 UTC by sienna011022

## 📚 이슈 번호
#325

## 📝 데이터베이스 변경 사항

## 💬 기타 사항
[에러 원인]
- 카테고리의 '이름'으로 쿼리문에서 조건을 걸다보니, 기타 와 미분류 처럼 부모가 다르지만 자식끼리 이름이 같은 경우, 중복된 값이 잡히고 있었습니다.

[해결 방안]
따라서, name이 아닌, entity자체로 비교하는 것으로 변경하였습니다

- 테스트 코드를 짜다가, 카테고리 리팩토링이 들어가고 있는 것으로 알아서, 포함시키지 않았습니다

2023-12-11 01:41 UTC, dahyen0o requested changes
카테고리 리팩토링은 진행 중이지 않으므로 테스트 코드 작성 부탁드립니다

2023-12-12 05:44 UTC, dahyen0o commented on src/test/java/com/floney/floney/book/BookLineRepositoryTest.java
> +    void analyzeByCategory() {
1. 가독성을 위해 given-when-then 주석 추가 부탁드립니다
```java
// given

// when

// then
```

2. 정렬 맞춰주세요! (actions on save에 정렬 옵션 안 켜놓으셨나요..?)

2023-12-12 05:44 UTC, dahyen0o commented on src/test/java/com/floney/floney/book/BookLineRepositoryTest.java
> +    }
https://velog.io/@guns95/Junit-%EB%82%B4%EB%B6%80%EA%B0%92-%EA%B2%80%EC%A6%9D%EA%B3%BC-Nested-%EC%B6%94%EC%B6%9C
위 글 참고해서 리팩토링해도 좋을 것 같습니다!

2023-12-13 13:39 UTC, sienna011022 commented on src/test/java/com/floney/floney/book/BookLineRepositoryTest.java
> +    void analyzeByCategory() {
2. 따로 변경되는 사항 없는데 어디 정렬 말하시는건가요?

2023-12-13 13:54 UTC, sienna011022 commented on src/test/java/com/floney/floney/book/BookLineRepositoryTest.java
> +    }
이 값은 객체가 복합 구조일 때, 사용하는 것이 맞는것 같습니다.
현재는 단순한게 string, double 타입만 가지고 있어서 get으로 해도 돼서, 오버 스펙 같아보여요

더불어, when에서 검사할 타겟이 list 형태라 in 형식을 사용하는 것이 맞아보입니다.

2023-12-14 07:02 UTC, dahyen0o commented on src/test/java/com/floney/floney/book/BookLineRepositoryTest.java
> +    void analyzeByCategory() {
커밋 확인하면 아시겠지만, 코드 수정하고 저장하실 때 자동 정렬된 것 같습니다

2023-12-14 07:21 UTC, sienna011022 commented on src/test/java/com/floney/floney/book/BookLineRepositoryTest.java
> +    void analyzeByCategory() {
어 전 그거 말고 test쪽에 태그 다셨길래 test쪽이 정렬 안된줄..!

2023-12-14 07:27 UTC, dahyen0o approved these changes

2023-12-14 08:51 UTC, merged