#342 hotfix : 카테고리 중복 생성 방지 검사 추가
Floney-2023/Floney-Server pull request #346
Opened 2023-12-21 13:12 UTC by sienna011022

## 📌 개요

카테고리 중복을 방지하기 위한 검사 메서드 추가

## ✅ 개발 내용

다음과 같이 중복된 이름의 카테고리를 추가하면, 에러가 반환되게끔 수정했습니다.
![image](https://github.com/Floney-2023/Floney-Server/assets/90383376/82a42d7a-7931-44d8-bfc1-bb6765548f3b)

기존 오기입 된 카테고리는 운영서버 DB에서 수동으로 지울 예정입니다.

2023-12-22 01:54 UTC, dahyen0o requested changes
1. 이번 이슈도 자산 데이터와 마찬가지로 동시성 문제가 발생할 수 있을 것으로 보입니다.
ex. 트랜잭션 A에서 카테고리 A 조회 (없음) → 트랜잭션 B에서 카테고리 A 조회 (없음) → 트랜잭션 A에서 카테고리 A 생성 → 트랜잭션 B에서 카테고리 생성

2. hotfix는 main을 base로 개발하고, main으로 PR 요청해야 합니다.

2023-12-23 09:47 UTC, sienna011022 commented
> 1. 이번 이슈도 자산 데이터와 마찬가지로 동시성 문제가 발생할 수 있을 것으로 보입니다.
>    ex. 트랜잭션 A에서 카테고리 A 조회 (없음) → 트랜잭션 B에서 카테고리 A 조회 (없음) → 트랜잭션 A에서 카테고리 A 생성 → 트랜잭션 B에서 카테고리 생성
> 2. hotfix는 main을 base로 개발하고, main으로 PR 요청해야 합니다.

1. 자산같은 경우는 60개의 데이터를 생성하기에, 그럴 가능성은 있어보였지만 카테고리 생성할 때는 단건으로 생성하기에 그럴 가능성이 없어보입니다. 뭔가 그렇게 생각하면, 결국엔 모든 api를 동시성 문제가 있다고 염두하고 바꿔야하지 않나요??
2. 아하 넵

2023-12-26 05:01 UTC, dahyen0o commented
@sienna011022 

>  뭔가 그렇게 생각하면, 결국엔 모든 api를 동시성 문제가 있다고 염두하고 바꿔야하지 않나요??

모든 API에 대해 동시성 문제를 고려해야 하는 건 맞다고 생각합니다. 그래서 저희가 출시 전에 전체적으로 살펴봤던 거고요. 그 중에서 동시적으로 요청되어도 문제 없는 경우(ex. 회원가입)이 있고 문제 있는 경우가 있을텐데 후자에 대해서만 살펴보면 되는 거고요!

2023-12-26 15:12 UTC, dahyen0o approved these changes

2023-12-26 23:02 UTC, merged