365 feature 기간 별 엑셀 추출 기능
Floney-2023/Floney-Server pull request #369
Opened 2024-01-10 14:59 UTC by sienna011022

## 📌 개요

사용자가 엑셀 추출 기간을 선택할 수 있다

## ✅ 개발 내용

- 이리저리 흩어져 있던 날짜 관련 상수를 enum으로 모았습니다.
-  사용자가 엑셀 추출 기간을 선택할 수 있게끔 했습니다
- DateFactory 메서드 명 리팩토링을 진행했습니다

2024-01-11 07:01 UTC, dahyen0o approved these changes
- 실제 코드 변경과 코드 정렬 코드는 최대한 분리해 커밋 부탁드립니다!
- DateFactory 가 대부분 DateDuration을 반환하고 DateDuration 과 관련된 비즈니스 로직이 존재한다면, DateDuration을 VO 객체로 취급해 DateFactory 내 관련 로직을 해당 객체로 옮기는 게 더 적절하지 않을까요?
- 새로 추가하신 테스트(Nested) 의 클래스 및 함수 이름과 구조 등 전체적인 코드를 DCI 패턴에 맞게 변경 부탁드립니다! 제가 미리 작성해놓은 UserAcceptanceTest 혹은 UserTest 를 참고하시면 쉽게 변경 가능할 겁니다

2024-01-11 07:01 UTC, dahyen0o requested changes
- 실제 코드 변경과 코드 정렬 코드는 최대한 분리해 커밋 부탁드립니다!
- DateFactory 가 대부분 DateDuration을 반환하고 DateDuration 과 관련된 비즈니스 로직이 존재한다면, DateDuration을 VO 객체로 취급해 DateFactory 내 관련 로직을 해당 객체로 옮기는 게 더 적절하지 않을까요?
- 새로 추가하신 테스트(Nested) 의 클래스 및 함수 이름과 구조 등 전체적인 코드를 DCI 패턴에 맞게 변경 부탁드립니다! 제가 미리 작성해놓은 UserAcceptanceTest 혹은 UserTest 를 참고하시면 쉽게 변경 가능할 겁니다

2024-01-11 07:01 UTC, dahyen0o requested changes
- 실제 코드 변경과 코드 정렬 코드는 최대한 분리해 커밋 부탁드립니다!
- DateFactory 가 대부분 DateDuration을 반환하고 DateDuration 과 관련된 비즈니스 로직이 존재한다면, DateDuration을 VO 객체로 취급해 DateFactory 내 관련 로직을 해당 객체로 옮기는 게 더 적절하지 않을까요?
- 새로 추가하신 테스트(Nested) 의 클래스 및 함수 이름과 구조 등 전체적인 코드를 DCI 패턴에 맞게 변경 부탁드립니다! 제가 미리 작성해놓은 UserAcceptanceTest 혹은 UserTest 를 참고하시면 쉽게 변경 가능할 겁니다

2024-01-13 03:56 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/dto/constant/DayType.java
> +    FIVE_YEAR_TO_DAY(60);
엑셀 때문에 나왔다기보다는, 플로니 소스 코드 이곳 저곳에서 날짜 관련 데이터를 private static final로 선언해서 상수화 시켰는데 , 중복 데이터가 많기도 하고,  한곳으로 모아지지가 않아서 관리가 어려웠습니다. 그래서 만든 enum입니다.

Excel관련 데이터는 ExcelDuration Enum으로 따로 파져있고요!

차라리 DayType, MonthType, YearType으로 쪼개서 관리해도 괜찮을 것 같긴 하네요

2024-01-13 07:40 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/dto/constant/DayType.java
> +    FIVE_YEAR_TO_DAY(60);
1. 관리가 어렵다 -> 구체적으로 예시를 들어주시겠어요?
지금 코드를 보면 DayType은 로직이 들어있지 않는 단순한 상수인데, 여러 곳에 있다해서 관리가 어려울 것 같진 않습니다. 오히려 관련 있는 클래스의 public 상수로 넣고 필요할 때 해당 상수를 다른 곳에서 참조하는 게 낫지 않을까요?

2. 중복 데이터가 많다 -> 이것도 잘 이해가 가지 않습니다.. 예시를 들어주시면 감사하겠습니다!

3. 개인적으로 현재 DateType 이라는 객체는 불필요하다고 생각합니다.
어떤 느낌이나면, email에 8자라는 길이 제한이 있고 nickname에 10자라는 길이 제한이 있으면 이 상수들을 LengthEnum 으로 묶은 느낌이예요... 불필요하게 묶어놓는 순간 하나의 객체에 대해 의존성이 커져서 변경에 유연하지 못한 코드가 되는것 같습니다

2024-01-13 10:36 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/dto/constant/DayType.java
> +    FIVE_YEAR_TO_DAY(60);
1,2번에 대한 예시는 혀냊 FIVE_YEAR_TO_DAY라는 60개월에 해당하는 enum이 서로 다른 클래스(자산,이월) 2군데서 사용중인데요.
만약 우리 정책이 바껴서 5년이 3년으로 줄었다면, 해당 60개월을 사용한 상수들을 찾아다니면서 고쳐줘야 합니다. 이런 측면에서 관리와 중복이 생긴다고 생각했습니다.

하지만, 세은님이 주신 3번 의견을 보니, 그런 측면에서 동의합니다. 그래서 다시 상수로 돌릴까 싶어요.
근데 제가 우려한 복잡도와 유지보수성을  극복할 수 있는 방법이 있을까요?

2024-01-15 12:04 UTC, dahyen0o requested changes
코드 스타일 공백 다시 한 번만 확인 부탁드립니다!!

2024-01-15 12:04 UTC, dahyen0o commented on src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
> +    private static final int SAVE_ASSET_DURATION = 60;
사실 5와 60은 같은 기간을 나타내는데, 이름만 봐서는 다른 기간처럼 보입니다. 그리고 이렇게 하면 5라는 값이 바뀌었을 때 60은 안 바뀌기도 하고요

찾아보니까 Period 라는 기간을 나타내는 자료구조가 있어서 이걸 활용하면 어떠신가요?

```java
    private static final Period ASSET_PERIOD = Period.ofYears(5);

    public void method() {
        int years = ASSET_PERIOD.getYears(); // 5
        int months = ASSET_PERIOD.getTotalMonths(); // 60
    }
```

2024-01-15 12:04 UTC, dahyen0o commented on src/main/java/com/floney/floney/analyze/service/CarryOverServiceImpl.java
> +    private final static int SAVE_CARRY_OVER_DURATION = 60;
얘도 위에 AssetService 에서 제안했던 것처럼 바꾸면 어떠신지..

2024-01-15 12:04 UTC, dahyen0o commented on src/main/java/com/floney/floney/common/domain/vo/DateDuration.java
> +    private static final int ASSET_DURATION = 5;
보니까 쓰이지도 않네요...!!

2024-01-15 12:27 UTC, sienna011022 commented on src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
> +    private static final int SAVE_ASSET_DURATION = 60;
아뇨 

SHOW_ASSET : 자산을 사용자에게 보여줄땐 6개월(인덱스 = 5로 해서 0-5) 기간으로 보여주고

SAVE_ASSET : 자산을 저장할땐 5년(5*12)입니다.

2024-01-15 12:32 UTC, sienna011022 commented on src/main/java/com/floney/floney/common/domain/vo/DateDuration.java
> +    }
흠 이게 약간 갈리는게..

get이란 단어를 작성하지 않음으로서 정말 도메인의 역할 처럼 보이게 메서드를 지을 수 있고, 
(@getter 선언x 전제)

어차피 같은 기능인데 어노테이션으로 제공해주는 get 함수를 쓰자는 입장이 있어요. 

저는 근데 일단은 후자가 더 편해서..후자로 갈게요..! 어떻게 생각하시는지는 궁금하네여

2024-01-15 12:34 UTC, sienna011022 commented on src/test/java/com/floney/floney/book/DateDurationTest.java
> +public class DateDurationTest {
세은님께서 테스트 이름을 블로그 참조해서 그렇게 바꾸라는건지 nested를 사용하고 테스트 명도 바꿔달라라는건지 모르겠어요

Nested 형태를 굳이 사용 안해도 되는 함수도 그렇게 표현해야하나요??

2024-01-15 16:22 UTC, dahyen0o commented on src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
> +    private static final int SAVE_ASSET_DURATION = 60;
아하 그러면 값을 5 → 6 으로 하는 게 나을 것 같습니다

2024-01-15 16:29 UTC, dahyen0o commented on src/test/java/com/floney/floney/book/DateDurationTest.java
> +public class DateDurationTest {
저 포스팅 보시면 아시겠지만 DCI 패턴은 단순히 테스트 이름을 바꾸는 게 아니라 테스트 구조 자체에 대한 패턴입니다. 
저번에 해당 패턴으로 작성한 UserAcceptanceTest 가 포함된 PR에서 아무 의견이 없으셔서 이걸 확인하고 동의하셨다고 생각했고요! 
`Nested 형태를 굳이 사용 안해도 되는 함수` 라는 게 뭔지 잘 모르겠지만, 이 패턴에서 계층 구조를 쓰는 건 테스트 결과의 가독성과 계층으로 describe, context, it을 분명하게 표시하기 위함입니다. 

<img width="359" alt="image" src="https://github.com/Floney-2023/Floney-Server/assets/64001680/4ac2fe80-f942-4d0f-9344-a051ed4858c9">

2024-01-15 16:34 UTC, dahyen0o commented on src/main/java/com/floney/floney/common/domain/vo/DateDuration.java
> +    }
만약 전자로 하려면, 이미 롬복으로 정의되어 있는 모든 객체들의 getter도 다 바꿔야하지 않을까요...?
저는 롬복을 통한 보일러플레이트 코드 생성을 선호해서 후자가 좋긴 합니다.

2024-01-16 03:12 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/repository/BookCustomRepositoryImpl.java
> +                .fetchOne();
![image](https://github.com/Floney-2023/Floney-Server/assets/90383376/362e0c63-8284-42fa-bb22-5352b999a9f2)

지금은 4로 잘 되어있긴한데, 8로 바뀐다음에 한번도 해당 페이지에 안 들어왔나봐요...

2024-01-16 03:28 UTC, sienna011022 commented on src/main/java/com/floney/floney/common/domain/vo/DateDuration.java
> +    public static DateDuration getStartAndEndOfMonth(String targetDate) {
[2번 의견]
우선 YearMonth만 필요하지 않습니다. 마지막 DatesDuration 생성자에서는 처음 받은 targetDate를 startDate로 사용합니다.

별개로 저는 오히려 앞에서 YearMonth를 파싱해 줘서 넣는게 더 비효율적이라고 생각합니다.
우선, BE와 IOS의 모든 날짜는 LocalDate형태로 소통하게끔 정해져 있습니다. 해당 메서드를 현재 8군데서 사용하고 있는데,이 메서드  호출 전에 항상 String을 localDate로 파싱하고, YearMonth를 파싱하는 코드 8번을 넣는게 더비효율적이라고  생각합니다.
차라리 LocalDate를 받는 게 더 재사용성 측면에서 효율적이라고 생각해요.

대신 내부에 private 메서드로, YearMonth 추출 함수를 빼기는 하겠습니다.

2024-01-16 03:37 UTC, sienna011022 commented on src/main/java/com/floney/floney/common/domain/vo/DateDuration.java
> +    private LocalDate endDate;
위에 의견 작성해놨습니다

2024-01-16 03:38 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/dto/constant/ExcelDuration.java
> +package com.floney.floney.book.dto.constant;
근데 애초에 constant라는 해당 패키지가 domain으로 가야 하는거 아닌가요?

/dto/constant  -> /domain/constant

2024-01-16 03:43 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/domain/vo/MonthLinesResponse.java
> +public class MonthLinesResponse {
이거 카테고리 재설계 머지된 바꾸겠습니다. 지금 건들이기엔 어차피 많이 바뀔것 같아서요

2024-01-16 03:44 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/controller/ExcelController.java
> +                         @RequestBody ExcelDownloadRequest downloadRequest,
어  혹시 참고할만한 레퍼런스가 있나요?
제 단순 생각으로는 우선 Post라 Body사양을 가지고 가고 싶기도하고, 그런 식별자가 최대한 안 드러나야 보안이 좋을 것 같은데  이유가 있으신가요

2024-01-16 03:47 UTC, sienna011022 commented on src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
> +    private static final int SAVE_ASSET_DURATION = 60;
흠 근데 `getAssetInfo()` 에서 시작달 = 현재 달 - 5개월로 해당 변수를 사용하기도 해서 그건 어려울 것 같아요

2024-01-16 03:53 UTC, sienna011022 commented on src/test/java/com/floney/floney/book/DateDurationTest.java
> +public class DateDurationTest {
아 저는 만약 depth가 1인 테스트인 경우 굳이 Nested로 해야하나 싶었습니다.

<pre>
DEPTH가 1이상인 코드?  - 예를 들어 세은님이 짜신 코드
회원 탈퇴 할 때(0 depth ) - 기타 탈퇴 사유가 비어있는 경우 (1 depth) - 에러를 반환한다 (2 depth)
회원 탈퇴 할 때(0 depth ) - 존재하지 않는 회원인 겨우 (1 depth) - 에러를 반환한다 (2 depth) 
같이 깊게 여러 경우의 수로 나뉜 경우(약간 트리구조..)
</pre>

![image](https://github.com/Floney-2023/Floney-Server/assets/90383376/0f51a99f-00fa-4e30-b293-b81ed4a286a4)
 제 테스트 코드 처럼(빨간박스) 단순히 로직 테스트할 코드가 1개(depth가 없음) 그걸 위해 하나하나 계층화 시키는게 더 과한 설계같단 생각을 해요

전 해당 패턴들이 가독성 떄문에 나왔다고 생각하는데, 오히려 이 경우는 가독성이 더 떨어지게 되는 거라고 생각해서
계층이 필요할 때만 Nested로 쓰는게 맞다고 생각합니다.

2024-01-16 04:03 UTC, sienna011022 commented on src/main/java/com/floney/floney/common/domain/vo/DateDuration.java
> +    }
훔...훔..LocalDate라는  util로 뺄수는 있을 거 같긴한데

현재 고작 2개의 클래스에 쓰이고 있다는 말이죠. 객체를 만드는 비용(관리)을 생각했을때 효율성과 재사용성이 있을까 싶긴해서 고민되네요. 그 당시에도 고민하다, 기간 관련이라 넣어놓긴했거든요.

아니면 그냥 함수 호출을 안하고  service에서 .withDayOfMonth를 호출할까 싶기도해요.

ex. before
<pre>
    @Override
    @Transactional
    public void addAssetOf(final BookLineRequest request, final Book book) {
        // 이체 내역일 경우 자산 포함 X
        // TODO: 파라미터에 BookLineRequest을 BookLine으로 대체한 후 검증 로직 추가
        if (BANK.getKind().equals(request.getFlow())) {
            return;
        }

        final LocalDate startMonth = DateDuration.getFirstDayOfMonth(request.getLineDate());

        for (int month = 0; month < SAVE_ASSET_DURATION; month++) {
            final LocalDate currentMonth = startMonth.plusMonths(month);
            assetRepository.upsertMoneyByDateAndBook(currentMonth, book, getMoney(request));
        }
    }

</pre>

After
<pre>
    @Override
    @Transactional
    public void addAssetOf(final BookLineRequest request, final Book book) {
        // 이체 내역일 경우 자산 포함 X
        // TODO: 파라미터에 BookLineRequest을 BookLine으로 대체한 후 검증 로직 추가
        if (BANK.getKind().equals(request.getFlow())) {
            return;
        }

        final LocalDate startMonth = request.getLineDate().withDayOfMonth(ONE_MONTH); //변경

        for (int month = 0; month < SAVE_ASSET_DURATION; month++) {
            final LocalDate currentMonth = startMonth.plusMonths(month);
            assetRepository.upsertMoneyByDateAndBook(currentMonth, book, getMoney(request));
        }
    }
</pre>

음..근데 뭔가 찝찝하네요 공통으로 쓰는 곳이 4군데 있어서..어떻게 하는게 좋으세요

2024-01-16 04:22 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/repository/BookCustomRepositoryImpl.java
> +                .fetchOne();
그럼 8로 적용된 코드들 재적용 부탁드립니다!

2024-01-16 04:47 UTC, dahyen0o commented on src/main/java/com/floney/floney/common/domain/vo/DateDuration.java
> +    }
1.  `객체를 만드는 비용(관리)` 이 이 상황에서 고려해야 할 정도로 큰 비용인가요? 제가 봤을 때는 관련 없는 코드를 하나의 객체에 쑤셔넣으면서 높은 결합도를 가진다는 단점이 훨씬 커보이네요..
2. 현재 고작 2개의 클래스에 쓰이고 있다 → 클린 코드든 OOP든 소프트웨어 철학에서 중요하게 여겨지는 개념 중 하나가 확장성인데, 앞으로 더 쓰일지도 모르는 상황에서 (물론 더 쓰이지 않을 수도 있지만) 미래를 대비하는 설계는 좋은 설계라고 생각합니다.
3. 따라서 저는 새로운 객체로 분리하는 게 좋다고 생각합니다. 굳이 덧붙이자면 클래스 이름은 `CalendarUtil` 정도..?

2024-01-16 06:00 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/repository/BookCustomRepositoryImpl.java
> +                .fetchOne();
엥 다시 4로 하면 되는거 아닌가요?

2024-01-16 12:29 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/repository/BookCustomRepositoryImpl.java
> +                .fetchOne();
네 4로 저장 부탁드립니다

2024-01-16 12:33 UTC, dahyen0o approved these changes

2024-01-16 12:37 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/controller/ExcelController.java
> +                         @RequestBody ExcelDownloadRequest downloadRequest,
아하 훔 근데 그건 Get 일 때는 맞다고 생각하는데(주로 그런 url은 조회 요청에서 보여진다고 생각) , 해당 API는  Post라 불필요하다고 생각합니다!

2024-01-16 12:37 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/dto/constant/ExcelDuration.java
> +package com.floney.floney.book.dto.constant;
옮겨놓겠습니다..ㅋㅋ

2024-01-16 12:45 UTC, merged