392 feature 반복 내역 설정
Floney-2023/Floney-Server pull request #398
Opened 2024-02-29 12:14 UTC by sienna011022

## 📌 개요

반복 내역 기능 개발

## ✅ 개발 내용

https://www.notion.so/fbcfe71062b14251991d576767db2fe7?pvs=4

2024-03-01 11:47 UTC, dahyen0o requested changes

2024-03-01 11:47 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/controller/BookController.java
> +    public ResponseEntity<?> deleteAllBookLineByRepeat(@RequestParam Long bookLineKey) {
- http method가 DELETE 인데 굳이 주소에 delete를 추가한 이유가 무엇인가요?
- bookLineKey -> bookLineId
- bookLine 식별자를 `/lines/{id}`로 주지 않고 param으로 받는 이유가 궁금합니다. path variable이 이럴때 쓰는거 아닌가요?

2024-03-01 11:47 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/controller/BookController.java
> +    public ResponseEntity<?> deleteRepeatLine(@RequestParam long repeatLineId) {
마찬가지로 `/repeat/{id}` 로 주면 되지 않을까요?

2024-03-01 11:47 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/domain/entity/RepeatBookLine.java
> +    private Book book;
BookUser에 Book이 있는데 따로 Book을 가져오신 이유가 뭔가요?

2024-03-01 11:47 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
> +        }
한 메서드에서 `반복 내역이 아닌 내역`과 `반복 내역` 생성을 둘 다 담당하는 이유가 뭔가요? 둘은 다른 비즈니스 로직인 것 같고, 아래 carryOver나 asset 생성 로직은 반복 내역에 의해 생성된 모든 가계부 내역들도 거쳐야 하지 않나요?

2024-03-01 11:47 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
> +    }
- 해당 bookLine이 반복 내역으로 생성된 건지 검증이 필요하지 않나요?
- 이름이 `inactiveByAllByAfter` -> `inactiveAllByAfter` 아닌가요?

2024-03-01 11:47 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
> +    }
영속성 컨텍스트를 비우는 작업이 없습니다.

2024-03-01 11:47 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
> +    }
- 영속성 컨텍스트를 비우는 작업이 없습니다.
- 이후 내역 중 특정 반복 내역으로 생성된 bookLine만 지우는거 아닌가요? 이 쿼리는 모든 가계부의 모든 가계부 내역 중 localDate 이후인 애들을 모두 지우는거 아닌가요?

2024-03-01 11:47 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/service/BookServiceImpl.java
> +            .orElseThrow(NotFoundRepeatBookLineException::new);
findByIdAndStatus() 아닌가요?

2024-03-01 11:47 UTC, dahyen0o commented on src/main/resources/db/migration/mysql/V11__add_repeat_book_line.sql
> +    `repeat_duration` varchar(20) NOT NULL,
가변 문자열이라 255로 설정해놓는게 좋지 않을까요?

2024-03-01 11:47 UTC, dahyen0o commented on src/test/java/com/floney/floney/fixture/CategoryFixture.java
> +public class CategoryFixture {
엔티티가 다른데 SubcategoryFixture / CategoryFixture 로 나눠야 하지 않을까요?

2024-03-01 11:47 UTC, dahyen0o commented on src/test/java/com/floney/floney/book/RepeatBookLineTest.java
> +package com.floney.floney.book;
왜 테스트 대상인 클래스와 패키지 위치를 맞추지 않고 Book 아래에 두셨나요?

2024-03-01 11:47 UTC, dahyen0o commented on src/test/java/com/floney/floney/book/RepeatBookLineTest.java
> +    }
테스트 메서드에서 (`it_...()`) 검증 로직이 있어야 하지 않을까요?

2024-03-01 11:47 UTC, dahyen0o commented on src/test/java/com/floney/floney/book/RepeatBookLineTest.java
> +        }
이 테스트 부터 아래 모든 테스트들을 보면 context가 context class에  없고 테스트 메서드에 있습니다.

2024-03-01 11:47 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/domain/entity/BookLine.java
> +    }
반복 내역이 만들어질 때 BookLine이 만들어지고 이후 수정이 없다면 굳이 setter로 추가하기보단 카테고리 연관관계를 지정할 때처럼 생성자에서 지정하는 게 나을 것 같습니다. 위 createByRepeatBookLine() 처럼요

2024-03-01 11:47 UTC, dahyen0o commented on src/test/java/com/floney/floney/fixture/CategoryFixture.java
> +    }
사용하지 않는데 왜 만드셨나요?
그리고 해당 카테고리들은 이미 DB에 존재합니다.

2024-03-01 11:47 UTC, dahyen0o commented on src/test/java/com/floney/floney/fixture/BookLineCategoryFixture.java
> +        Category assetLineCategory = Category.builder().name(CategoryType.ASSET).build();
이미 DB에 존재합니다.

2024-03-01 12:14 UTC, sienna011022 commented on src/main/resources/db/migration/mysql/V10__change_idx_in_asset.sql
> +ALTER TABLE `asset`
제 로컬에서는 이전 쿼리는 에러가 났었고, 세은님 머지 되기전에 고친 내용이라 현재는 수정은 철회하겠습니다

2024-03-01 12:14 UTC, sienna011022 commented on src/main/resources/db/migration/mysql/V11__add_repeat_book_line.sql
> +    `repeat_duration` varchar(20) NOT NULL,
repeat_duration 말씀하시는거면, `RepeatDuration` enum을 사용해서 20 충분하다고 생각하는데 가변 문자열이라고 생각하신 이유가 어떤 상황인가요?

2024-03-01 12:14 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/controller/BookController.java
> +    public ResponseEntity<?> deleteAllBookLineByRepeat(@RequestParam Long bookLineKey) {
path variable 이랑 request param이랑 거의 유사한 기능이라고 생각합니다.

물론 @PathVariable은 값을 하나만 받아올 수 있으므로, 쿼리스트링 등을 이용한 여러 개 데이터를 받아올 때는 @RequestParam을 쓰기도 하고요

현재 우리 상황에서는 해당 하지 않기에, 사실 뭘 선택하든 상관은 없겠죠,
param값으로 보내게 되면 `books/repeat/?repeatBookLine = 1` 뭐 이런식으로 보여지게 돼서 명확해서 좋기도 한데, 그냥 개인 선호도라고 생각합니다

2024-03-01 12:17 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/domain/entity/RepeatBookLine.java
> +    private Book book;
RepeatBookLine은 주로 가계부 기준으로 조회,삭제가 이루어지기에 , 만약 book 속성을 안넣으면, Bookuser에서 join으로 항상 꺼내오는 비용이 발생합니다. 애초에 처음 초기화 될때 book을 넣어주면 그런 비용을 훨씬 절감할 수 있음에 넣어놨습니다

2024-03-01 12:17 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
> +        }
아 그러네요!!

2024-03-01 12:19 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
> +    }
1. 경민님이 검증해서 보내주기로 했습니다만, 방어 코드를 추가하도록 하겠습니다
2. 넵 오타 수정할게요

2024-03-01 13:52 UTC, sienna011022 commented on src/test/java/com/floney/floney/book/RepeatBookLineTest.java
> +package com.floney.floney.book;
이해를 못했는데, RepeatBookLine은 book도메인 내부에 속해있는데 그럼 어디에 있어야하나요?

2024-03-01 13:54 UTC, sienna011022 commented on src/test/java/com/floney/floney/book/RepeatBookLineTest.java
> +    }
이해를 못했는데 이건 공통 검증 메서드를 따로 빼놓은거고 각 테스트 마다 it 안에서 해당 함수를 호출합니다

<pre>
  @Nested
        @DisplayName("매주를 선택한 경우")
        class Context_With_EveryWeek {

            @Test
            @DisplayName("매주 같은 요일에 가계부 내역이 생성된다")
            void it_returns_bookLines() {
                final List<BookLine> bookLines = repeatBookLine.bookLinesBy(RepeatDuration.WEEK);

                LocalDate startDate = lineDate.plusDays(1);
                LocalDate endDate = lineDate.plusYears(REPEAT_YEAR);
                long daysBetween = ChronoUnit.DAYS.between(startDate, endDate);

                assertBookLineSameWithRepeat(bookLines, repeatBookLine); //호출
                assertThat(bookLines.size()).isEqualTo(daysBetween / 7);
                assertThat(bookLines.get(0).getLineDate()).isEqualTo(lineDate.plusDays(7));

            }
        }
     </pre>

2024-03-01 13:56 UTC, sienna011022 commented on src/test/java/com/floney/floney/book/RepeatBookLineTest.java
> +        }
이해를 못했어요 다시 설명부탁드립니다

2024-03-01 13:58 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/domain/entity/BookLine.java
> +    }
그것도 좋긴한데, 제가 새로 고쳐서 올린 커밋 참고하시면 중복을 줄이고자 bookLine은 반복이든 아니든 먼저 생성하려고 해서,후자의 상황을 택하면 제안 주신 로직이 불가능합니다

2024-03-01 13:59 UTC, sienna011022 commented on src/test/java/com/floney/floney/fixture/CategoryFixture.java
> +    }
아 bookLineServiceTest를 하나 추가했는데, service 테스트는 db랑 의존이 없어서 mock으로 만들어줬어야했습니다.

2024-03-01 14:00 UTC, sienna011022 commented on src/test/java/com/floney/floney/fixture/BookLineCategoryFixture.java
> +        Category assetLineCategory = Category.builder().name(CategoryType.ASSET).build();
도메인 테스트 같은 경우 DB에서 찾을 수 없지 않나요? 현재 사용하는 부분이 `RepeatBookLineTest`입니다

2024-03-01 14:02 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/controller/BookController.java
> +    public ResponseEntity<?> deleteRepeatLine(@RequestParam long repeatLineId) {
위에서 답변 드렸습니다

2024-03-01 14:39 UTC, dahyen0o commented on src/test/java/com/floney/floney/book/RepeatBookLineTest.java
> +package com.floney.floney.book;
book 아래 패키지 구조(domain, controller,...) 까지 따라가야 되지 않나 싶어서요
상위 패키지에 클래스를 몰아넣으면 너무 많기도 하고 보통 프로덕션의 패키지 구조를 따라간다고 알고 있습니다

2024-03-01 14:44 UTC, sienna011022 commented on src/test/java/com/floney/floney/book/RepeatBookLineTest.java
> +package com.floney.floney.book;
아하 테스트 같은 경우는 따로 이슈 파서 정리하는건 어떨까요

2024-03-01 14:46 UTC, dahyen0o commented on src/test/java/com/floney/floney/book/RepeatBookLineTest.java
> +    }
제 말은 저 it() 메서드만 봤을 때 검증 코드가 함수로 빠져있는데, 그러면 테스트 메서드를 보고 어떤 걸 검증하는 지 한눈에 파악이 힘들어보여요.

```java
void it() {
	// ...
	assertAll(
		// assertBookLineSameWithRepeat 내 assert 구문들
		// ...
		assertThat(bookLines.size()).isEqualTo(daysBetween / 7);
        assertThat(bookLines.get(0).getLineDate()).isEqualTo(lineDate.plusDays(7));
	);
}
```

보통 한 테스트에 여러 assert 를 지향하기도 해서 이런식으로 묶는게 낫지 않을까요?

2024-03-01 14:49 UTC, dahyen0o commented on src/test/java/com/floney/floney/book/RepeatBookLineTest.java
> +        }
```java
@Nested
@DisplayName("매일을 선택한 경우")
class Context_With_EveryDay {

	RepeatDuration rd =  RepeatDuration.EVERYDAY;

    @Test
    @DisplayName("매일 가계부 내역이 생성된다")
    void it_returns_bookLines() {
        final List<BookLine> bookLines = repeatBookLine.bookLinesBy(rd);

        LocalDate startDate = lineDate.plusDays(1);
        LocalDate endDate = lineDate.plusYears(REPEAT_YEAR);
        long daysBetween = ChronoUnit.DAYS.between(startDate, endDate);

        assertBookLineSameWithRepeat(bookLines, repeatBookLine);
        assertThat(bookLines.size()).isEqualTo(daysBetween);
        assertThat(bookLines.get(0).getLineDate()).isEqualTo(lineDate.plusDays(1));

    }
}
```

테스트하기 위해 사용될 context가 저 class의 멤버 변수로 빠져야 하지 않냐는 말이었어요

2024-03-01 15:40 UTC, sienna011022 commented on src/test/java/com/floney/floney/book/RepeatBookLineTest.java
> +    }
그냥 공통화 안하고 메서드 푸르라는 말씀인가요? 근데 검증 코드가 길어서 각 메서드에 들어가면 넘 지저분 하지 않나요..?

2024-03-01 15:47 UTC, dahyen0o commented on src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
> +        if (TRANSFER.getMeaning().equals(lineCategory.toString())) {
`Transfer.equals(lineCategory.getName())` 으로 하면 되지 않나요?

2024-03-01 15:50 UTC, dahyen0o commented on src/main/java/com/floney/floney/analyze/service/CarryOverService.java
> +    void createCarryOverByAddBookLine(BookLine bookLine);
사소하지만 다른 carryOver 메서드 이름과 다르게 ByAddBookLine을 붙이신 이유가 있나요?

2024-03-01 15:53 UTC, dahyen0o commented on src/test/java/com/floney/floney/book/BookLineServiceTest.java
> +public class BookLineServiceTest {
왜 ServiceTest를 추가하셨나요?

2024-03-01 16:00 UTC, dahyen0o commented on src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
>          }
세정님 이게 제가 작성했던 거라 대신 답변하자면.. 객체지향 생활 체조원칙에서 메서드 당 최대 뎁스를 2로 제한하는데 (긴 뎁스 지향) 말씀하신대로 하면 더 좋은 점이 있나요?

2024-03-01 16:03 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
> +            return createBookLineByNotRepeat(bookLine);
1. 우선 프론트쪽에서 가능한지 확인해봐야 할 듯합니다(버튼은 하나니깐요)
2. 전 딱히 다르다고 생각하진 않습니다. 자산 데이터나 이월 데이터 처럼 가계부 내역 추가로 생기는 부가적인 효과라고 생각합니다.

2024-03-01 16:06 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
> +            return createBookLineByNotRepeat(bookLine);
아 다른 버튼인 줄 알았네요. 알겠습니다

2024-03-01 16:30 UTC, sienna011022 commented on src/main/resources/db/migration/mysql/V11__add_repeat_book_line.sql
> +    `repeat_duration` varchar(20) NOT NULL,
훔 사용자가 바꾸는 부분이 아니라서 255까지는 투머치라고 생각합니다. 의견 고려하여 넉넉히 100으로 하겠습니다

2024-03-01 16:35 UTC, sienna011022 commented on src/test/java/com/floney/floney/book/BookLineServiceTest.java
> +public class BookLineServiceTest {
반복 내역 생성으로 인해 가계부 내역 생성 api가 변경됐는데 계속 postman 쏘는 것보다 하나 만들어놓는게 더 효율적이라서 하나만 후딱 만들었는데, 차후에 이부분은 아예 뜯어 고쳐야할것 같아여

2024-03-02 01:12 UTC, sienna011022 commented on src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
> +        if (TRANSFER.getMeaning().equals(lineCategory.toString())) {
우선, 단순 toString으로 잡은건 제 실수가 맞습니다(객체의 참조값이 반환됨)
하지만 제안 주신 내용은 getMeaning()은 반환값이 String이고, getName()은 반환타입이 CategoryType이기 때문에
![image](https://github.com/Floney-2023/Floney-Server/assets/90383376/4626a7ce-8594-4bc9-841c-d96d9dbab405)

`CategoryFixture.incomeCategory().getName().getMeaning()` 이렇게 수정하면 말이 됩니다
![image](https://github.com/Floney-2023/Floney-Server/assets/90383376/900efbb7-b668-4270-b1b1-ab43c0fbace0)

  Category엔티티의 name이라는 필드가 사용하기에 너무 헷갈려서, categoryType으로 수정하겠습니다

2024-03-02 01:14 UTC, sienna011022 commented on src/main/java/com/floney/floney/analyze/service/CarryOverService.java
> +    void createCarryOverByAddBookLine(BookLine bookLine);
아 리팩토링하면서, 바뀌었는데 원복을 놓친 부분같습니다. 감사합니다

2024-03-02 01:57 UTC, dahyen0o commented on src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
> +        if (TRANSFER.getMeaning().equals(lineCategory.toString())) {
네 저는 굳이 enum이 있는데 meaning을 가져와 String으로 비교해야 하냐는 거였어요.

2024-03-02 03:50 UTC, sienna011022 commented on src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
> +        if (TRANSFER.getMeaning().equals(lineCategory.toString())) {
아~ 그러네여 ㅋㅋ

2024-03-03 04:56 UTC, dahyen0o approved these changes

2024-03-03 04:56 UTC, dahyen0o commented on src/main/java/com/floney/floney/analyze/service/CarryOverServiceImpl.java
> +        for (int i = 0; i <= SAVE_CARRY_OVER_DURATION; i++) {
이거 0~60이라 총 61달 아닌가요?

2024-03-03 04:56 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
> +        return bookLineRepository.findAllOutcomes(allOutcomesRequest).stream().map(DayLines::from).toList();
굳이 한 줄에 몰아넣으신(?) 이유는 무엇인가요
전체적으로 이 클래스 내 코드들을 한 줄로 몰아 넣으셨던데 한 줄이 너무 길어서 가독성이 떨어집니다

2024-03-03 04:56 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
> +            bookLineRepository.save(line);
변경 감지를 이용 안하고 명시적으로 save하는 이유는 뭔가요?

2024-03-03 04:56 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/service/BookServiceImpl.java
> +        //TODO : 이벤트 처리
이게 정확히 무슨 주석인진 모르겠지만 이벤트를 처리하고 머지해야 하는거 아닌가요?

2024-03-03 04:56 UTC, dahyen0o commented on src/main/resources/db/migration/mysql/V11__add_repeat_book_line.sql
> +    `repeat_duration` varchar(100) NOT NULL,
그냥 255로 하면 안되나요...? 어차피 가변 문자열(varchar)이라 상관없는데요

2024-03-03 04:56 UTC, dahyen0o commented on src/test/java/com/floney/floney/book/domain/entity/BookTest.java
> +public class BookTest {
클래스에 DisplayName이 없습니다

2024-03-03 04:56 UTC, dahyen0o commented on src/test/java/com/floney/floney/book/domain/entity/BookTest.java
> +    }
Nested 컨벤션이 지켜지지 않았습니다
(혹시나 컨벤션 생성 이전의 테스트라면 다른 이슈에서 수정하는게 좋겠네요)

2024-03-03 04:56 UTC, dahyen0o commented on src/test/java/com/floney/floney/book/domain/entity/CarryOverTest.java
> +            CarryOver carryOver;
'수입 내역'이 주어지면 인데 정작 주어진건 CarryOver네요..?
그리고 어떤 기준으로 D 클래스 또는 C 클래스 멤버 변수를 나누는건지 모르겠습니다.
테스트 간 설정 공유는 신중해야 하는데 예시로 bookLIne은 테스트 별로 다름에도 왜 멤버 변수로 공유되는지 모르겠어요

2024-03-03 04:56 UTC, dahyen0o commented on src/main/java/com/floney/floney/analyze/service/CarryOverServiceImpl.java
>              }
생각해보면 asset 처럼 여기도 동시성 문제가 발생하지 않을까요?

2024-03-03 04:56 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/domain/entity/RepeatBookLine.java
> +        // 오늘 날짜를 포함하여 5년치를 생성.
상수값에 따라 수치가 달라지는 데 굳이 주석으로 설명을 추가하지 않아도 될 것 같습니다.

2024-03-03 05:26 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/service/BookServiceImpl.java
> +        //TODO : 이벤트 처리
아, 똑같은 코드가 bookLineService에도 있고 bookService에도 있어서

뭔가 bookService가 가지고 있어야할 역할이 아니라고 생각했습니다.

BookService쪽에서 bookLineService 가 가진 메서드를 시행하도록 하고 싶었는데 서비스끼리 너무 의존이 되니깐 예전에 세은님이 도입하신 이벤트 처리를 하면 좋지 않을까 싶었어요!!

2024-03-03 05:29 UTC, sienna011022 commented on src/test/java/com/floney/floney/book/domain/entity/BookTest.java
> +    }
넹 맞아요 이후 이슈에서 한번 정리해보아요

2024-03-03 05:32 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
> +        return bookLineRepository.findAllOutcomes(allOutcomesRequest).stream().map(DayLines::from).toList();
아 이거 제가 intellij custom break 설정을 잘못 건드렸더니 다 이렇게 변해버려서 최대한 보이는 족족 다시 원복중인데 놓치는게 있네요 이후에도 틈틈히 원복하겠습니다..

2024-03-03 05:54 UTC, sienna011022 commented on src/test/java/com/floney/floney/book/domain/entity/CarryOverTest.java
> +            CarryOver carryOver;
1. 흠..`이월` 내역이라고 정정하겠습니다.
2.  D클래스에는 테스트 할 대상이 아니라  테스트 대상을 하기 위한 빌드업(?) 하는 애들은 D클래스에 변수로,  C클래스에는 테스트 대상이 명시적으로 보이게 하기 위해 Conext내부에 정의하여 중복 코드를 줄이고 싶었는데요. 

말씀 듣고 보니 여러모로 혼동 및 공유가 될것 같아서 변수에 재할당이 되는 친구들은 C내부로 옮기겠습니다

2024-03-03 05:55 UTC, sienna011022 commented on src/test/java/com/floney/floney/book/domain/entity/BookTest.java
> +public class BookTest {
Nested 도입 이전 테스트 코드라 나중에 이슈로 한번에 처리해야할것 같습니다~

2024-03-03 06:24 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
> +            bookLineRepository.save(line);
전 save를 명시적으로 코드로 작성해서 혹시 작동안할 상황에 대해 대비하는 방어코드 (영속화가 제대로 안됐거나, Transactional이 빠졌거나) 작성이 가능해진다고 생각합니다.
또한 개발자가 코드 동작 과정에 대해 명시적으로 알 수 있다고 생각합니다.

더불어 이번에 개발하다가 발견한 이상한 점이 하나 있는데, 우선 save 명시적으로 넣어놓고 이슈는 보고 있습니다.

 `BookLinServiceImpl`의  deleteLine()의 원래 코드가
 다음과 같았는데여.
<pre>
    @Override
    @Transactional
    public void deleteLine(final Long bookLineId) {
        final BookLine savedBookLine = bookLineRepository.findByIdAndStatus(bookLineId, ACTIVE).orElseThrow(NotFoundBookLineException::new);
        savedBookLine.inactive();
}
</pre>

원래라면 변경감지가 작동해서 db 에서 bookLine status가 INACTIVE로 바껴야하는데 API는 정상 실행됨에도 INACTIVE로 안바껴서 우선 명시적으로 save()를 호출해서 해결했습니다.

왜 그런지 아시나요?

2024-03-03 06:29 UTC, sienna011022 commented on src/main/resources/db/migration/mysql/V11__add_repeat_book_line.sql
> +    `repeat_duration` varchar(100) NOT NULL,
네 메모리상으로 똑같긴한데요. 제 3자가 와서 DB를 볼 때, 단순 의미없는 255보단 100으로 지정했을때, repeat_duration에 대한 길이는 이정도구나 관리가 되지 않을까요..?

2024-03-03 06:40 UTC, sienna011022 commented on src/main/java/com/floney/floney/analyze/service/CarryOverServiceImpl.java
>              }
따로 이슈로 파서 처리하겠습니당

2024-03-03 06:49 UTC, merged