409 fix 반복 내역 성능 개선
Floney-2023/Floney-Server pull request #411
Opened 2024-03-07 10:49 UTC by sienna011022

## 📌 개요

반복 내역 성능 개선

## ✅ 개발 내용

 **_EVERYDAY 로 가계부 내역 추가 시, 수치 확인 후 공유 부탁드립니다_**

- 우선 통과 안하는 테스트는 성능 개선 검토 후 통과하게 만들겠습니다
- 자산, 이월 설정 수치 잘 업데이트 되는거 확인했습니다.
- mysql에 `?&rewriteBatchedStatements=true` 설정 해주셔야합니다 `  url: jdbc:mysql://localhost:3306/floney_local?&rewriteBatchedStatements=true`
- dev,prod는 제가 `?&rewriteBatchedStatements=true` 해놨습니다
- 작디 작은 램 부족도 문제인것 같습니다

2024-03-07 13:39 UTC, dahyen0o commented
### 로컬 테스트

조건 

- 이월 설정 ON
- 반복 내역 '매일'

실행 시간

- 1년 기준: 3.5 초
- 3년 기준: 37.7 초
- 5년 기준: 53.7 초

2024-03-07 14:19 UTC, dahyen0o approved these changes
asset, carryOver 등 도메인 로직 관련 오류 없는 건 확인하셨다고 생각하겠습니다. (테스트를 얼른 추가해야겠네요..)

2024-03-07 14:21 UTC, dahyen0o requested changes
아 secret 설정 커밋 반영 안되어있습니다

2024-03-07 14:33 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/repository/CarryOverJdbcRepository.java
> +            "VALUES (?,?,?,now(),now(),?) ON DUPLICATE KEY UPDATE money = money + VALUES(money), updated_at = NOW()";
전 저게 문법으로 알고 있습니다.
쉽게 말해서, 내가 작성한 파라미터 중 money를 있는 money와 더해라. 즉 `내가 작성한` 파라미터를 뽑기 위해 `VALUES(money)` 명시하는걸로 앎니다

https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html

2024-03-08 10:21 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/domain/entity/CarryOver.java
>                  .book(bookLine.getBook())
지금 더해야 될 때랑 빼야 될 때(delete/add)를 도메인에서 구별하고 쿼리에서는 똑같이 더해주고 있는데, Asset 쪽 개발했을 때 경험 상 많이 헷갈렸어서 이월 내역 추가/삭제 쿼리를 구분하는 게 좋을 것 같습니다.

정리하면 도메인에서는 무조건 INCOME - 양수 & OUTCOME - 음수, 쿼리에서 더하기 및 빼기 따로 구현

2024-03-08 10:43 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/domain/entity/CarryOver.java
>                  .book(bookLine.getBook())
음..전 이건 도메인의 비즈니스 로직인데, 쿼리쪽에서 관리를 할 부분은 아니라고 생각합니다.
도메인쪽에서 관리하는게 더 테스트하기도 용이하고요

2024-03-08 10:49 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/domain/category/CategoryType.java
> +    }
같은 함수가 여러 군데서 쓰이고 있었고, 객체끼리 서비스에서 비교시키는 것보다, enum 한테 물어봐서 관련 로직을 한곳으로 모이는 방향이 낫다고 판단했습니다

2024-03-08 11:01 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/domain/entity/CarryOver.java
>                  .book(bookLine.getBook())
그럼 차라리 delete() 를 호출하면 부호를 뒤집은 값을 호출하는 게 낫지 않을까요?
제 말의 요점은 내역 종류(지출, 수입) 에 따라 값의 부호는 고정이 되어야 하는데, delete로 빼기 연산을 수행해야 할 때 해당 값을 빼주는 게 아니라 (-)를 붙인 값을 생성하는 게 논리적으로 맞지 않다는 거였어요

2024-03-08 12:13 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/domain/category/CategoryType.java
> +    }
아 생각해보니 그것도 enum에서 주는 코드네요 넵 반영하겠습니다

2024-03-08 12:18 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/domain/entity/CarryOver.java
>                  .book(bookLine.getBook())
![image](https://github.com/Floney-2023/Floney-Server/assets/90383376/b3ea507c-07da-4c41-a503-e7f546eb2bc3)

이런식으로 변경하시는거 말하시는건가요???

2024-03-08 12:21 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/domain/entity/CarryOver.java
>                  .book(bookLine.getBook())
delete 할 때 부호를 바꾼 새 CarryOver 객체를 생성해서 반환해서 넣어주면 좋을 것 같습니다!

2024-03-09 03:22 UTC, dahyen0o approved these changes

2024-03-09 03:22 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/domain/entity/CarryOver.java
> +    }
안쓰는거죠?

2024-03-09 05:40 UTC, merged