#442 feature : 내역이 존재하지 않을 경우 반복 내역 삭제
Floney-2023/Floney-Server pull request #444
Opened 2024-03-25 01:28 UTC by sienna011022

## 📌 개요

가계부 내역이 존재하지 않을 경우 반복 내역 삭제

## ✅ 개발 내용

- 가계부 내역이 하나도 존재하지 않을 경우 반복 내역 삭제
- 반복 내역 조회 시, 해당 로직 수행

2024-03-26 14:39 UTC, dahyen0o requested changes
코드 스타일 설정 잘못되어있는 것 같은데(인덴트) 확인 후 수정부탁드립니다

2024-03-28 11:49 UTC, sienna011022 commented
> 코드 스타일 설정 잘못되어있는 것 같은데(인덴트) 확인 후 수정부탁드립니다

재설정후 푸쉬했습니다

2024-03-28 16:09 UTC, dahyen0o approved these changes

2024-03-28 16:09 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/service/BookServiceImpl.java
> +            .collect(Collectors.toList());
`toList()` 만 써도 되지 않나요?

2024-04-02 11:36 UTC, merged