#439 feat: 즐겨찾기 추가 구현
Floney-2023/Floney-Server pull request #455
Opened 2024-04-29 08:26 UTC by dahyen0o

## 📌 개요

즐겨찾기 추가 API 구현

## ✅ 개발 내용

- 가계부 당 즐겨찾기 개수 10개 제한 구현
- 가계부원이 아닌 사용자가 즐겨찾기 추가 요청 시 제한 구현
- 관련 인수 테스트 추가

2024-04-29 08:27 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/dto/request/FavoriteCreateRequest.java
> +public record FavoriteCreateRequest(
최근 record 객체를 접했는데, 롬복 없이 필요 메서드 자동 생성 & 멤버 변수 자동 불변 등이 마음에 들어 DTO 객체에 사용했습니다.

2024-04-29 08:29 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/service/FavoriteServiceImpl.java
> +        final int favoriteSize = favoriteRepository.findAllExclusivelyByBookAndStatus(book, ACTIVE).size();
즐겨찾기 개수를 계산하는 과정에서 동시성 문제가 발생할 수 있어 비관적 락을 추가했습니다.

2024-04-29 08:30 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/service/FavoriteServiceImpl.java
> +        }
이미 10개가 넘개 저장되어 있으면 동시성 다루기에 실패했으므로 error 수준의 로그가 출력되어 슬랙 알림이 오도록 했습니다.

2024-04-29 08:30 UTC, dahyen0o commented on src/main/java/com/floney/floney/common/exception/book/FavoriteSizeInvalidException.java
> +    }
예외 로그를 해당 예외  생성자에서 찍도록 해봤습니다. 이게 가장 편한 방법 같은데 어떠세요?

2024-04-29 11:13 UTC, sienna011022 commented
빌드 에러 해결 바랍니다!

2024-04-29 11:13 UTC, sienna011022 requested changes

2024-04-29 11:13 UTC, sienna011022 commented on src/main/java/com/floney/floney/book/service/FavoriteServiceImpl.java
> +        final Favorite favorite = Favorite.builder()
늘 해오던 것 처럼 entity 내부로 캡슐화 시키지 않았는지 궁금합니다

2024-04-29 11:13 UTC, sienna011022 commented on src/main/java/com/floney/floney/common/exception/book/FavoriteSizeInvalidException.java
> +    }
일단 문제는 없어보입니다.

2024-04-30 05:35 UTC, dahyen0o commented on src/main/java/com/floney/floney/book/service/FavoriteServiceImpl.java
> +        final Favorite favorite = Favorite.builder()
고민했는데 다음과 같은 이유로 우선 이렇게 작업했습니다.
1. DTO 객체의 변화가 도메인 내부 코드에 영향을 주는게 맞나?
2. 어차피 카테고리 객체를 외부에서 불러와야 하므로 정적 팩토리 메서드 생성 시 파라미터가 4개가 됨

2024-04-30 12:34 UTC, sienna011022 approved these changes

2024-05-01 02:49 UTC, merged